<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Meteor HTML CSS Template</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
        <link rel="stylesheet" href="<themeDir>/css/tooplate-style.css">
        <link rel="stylesheet" href="<themeDir>/css/fontAwesome.css">
        @addOnCss;

        <script src="<themeDir>/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>

<body>
    <header class="header">
        <div class="container">
            <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                    <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand scroll-top">
                        <div class="logo">@siteTitle;</div>
                    </a>
                </div>
                <!--/.navbar-header-->
                <div id="main-nav" class="collapse navbar-collapse">
                    @menu;
                </div>
                <!--/.navbar-collapse-->
            </nav>
            <!--/.navbar-->
        </div>
        <!--/.container-->
    </header>
    <!--/.header-->

    <section>
      @slider;
    </section>

    <div id="about" class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h4>@sectionHeading_1;</h4>
                        <div class="line-dec"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="service-item first-service">
                        <div class="icon"></div>
                        <h4>@serviceItemHeading_1;</h4>
                        <p>@serviceItemDescription_1;</p>
                    </div>
                </div>
                 <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="service-item second-service">
                        <div class="icon"></div>
                        <h4>@serviceItemHeading_2;</h4>
                        <p>@serviceItemDescription_2;</p>
                    </div>
                </div>
                 <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="service-item third-service">
                        <div class="icon"></div>
                        <h4>@serviceItemHeading_3;</h4>
                        <p>@serviceItemDescription_3;</p>
                    </div>
                </div>
                 <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="service-item fourth-service">
                        <div class="icon"></div>
                        <h4>@serviceItemHeading_4;</h4>
                        <p>@serviceItemDescription_3;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="what-we-do">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="left-text">
                        <h4>@whatWeDoStripHeading;</h4>
                        <p>@whatWeDoStripContent;</p>
                        <ul>
                            <li>
                                <div class="white-button">@whatWeDoStripLink_1;</div>
                            </li>
                            <li>
                                <div class="primary-button">@whatWeDoStripLink_2;</div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="right-image">
                        @whatWeDoStripImage_1;
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="portfolio" class="page-section">
        <div class="content-wrapper">
            <div class="inner-container container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-heading">
                            <h4>@portfolioSectionHeader;</h4>
                            <div class="line-dec"></div>
                        </div>
                    </div>
                </div>
                <div class="projects-holder-3">
                    <div class="">@portFolioDescription;</div>
                    <div class="projects-holder">
                        <div class="row">
                            <div class="col-md-3 col-sm-6 project-item mix workspace">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_1;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_1;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix workspace">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_2;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_2;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix technology">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_3;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_3;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix city">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_4;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_4;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix nature">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_5;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_5;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix technology">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_6;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_6;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix workspace">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_7;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_7;
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-3 col-sm-6 project-item mix city">
                              <div class="thumb">
                                  <div class="image">
                                    @projectImage_8;
                                  </div>
                                  <div class="hover-effect">
                                    @projectImageZoomIconLink_8;
                                  </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="blog" class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h4>@blogSectionHeading;</h4>
                        <div class="line-dec"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="blog-item b1">
                        <div class="thumb">
                            @blogImage_1;
                            <div class="text-content">
                                <h4>@blogHeading_1;</h4>
                                <span>@blogSubheading_1;</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="blog-item second-blog b2">
                        <div class="thumb">
                            @blogImage_2;
                            <div class="text-content">
                              <h4>@blogHeading_2;</h4>
                              <span>@blogSubheading_2;</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="blog-item b3">
                        <div class="thumb">
                              @blogImage_3;
                            <div class="text-content">
                              <h4>@blogHeading_3;</h4>
                              <span>@blogSubheading_3;</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div id="fun-facts">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="fact-item">
                        <div class="counter" data-count="926">@statsCount_1;</div>
                        <span>@statsTitle_1;</span>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="fact-item">
                        <div class="counter" data-count="214">@statsCount_2;</div>
                        <span>@statsTitle_2;</span>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="fact-item">
                        <div class="counter" data-count="118">@statsCount_3;</div>
                        <span>@statsTitle_3;</span>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="fact-item">
                        <div class="counter" data-count="16">@statsCount_4;</div>
                        <span>@statsTitle_4;</span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="contact" class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h4>@contactFormTitle;</h4>
                        <div class="line-dec"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="map">@locationMap;</div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                      @contactForm;
                    </div>
                </div>
            </div>
        </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="copyright-text">@footerTextLeft;</div>
                </div>
                <div class="col-md-6">
                    <div class="social-icons">@footerLinks;</div>
                </div>
            </div>
        </div>
    </footer>



    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="<themeDir>/js/vendor/bootstrap.min.js"></script>

    <script>
      $(document).ready(function(){
          $("#meteor").carousel({
            wrap: true,
            interval: 500,
            pause: false
          });
      });
    </script>
    <script src="<themeDir>/js/plugins.js"></script>
    <script src="<themeDir>/js/main.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        // navigation click actions
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 50;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
    @addOnContent;
    @addOnJs;
</body>
</html>
