<?php
  $this->addOnCss = '<link rel="stylesheet" href="'.$this->baseUrl().'/ui_alte/dist/css/tree.css">';
  $this->addOnJs = '<script src="'.$this->baseUrl().'/ui_alte/dist/js/bootstrap-tree.js"></script>';
?>
<?php if(isset($this->message)) echo '<div class="row"><div class="col-lg-12">'.$this->message.'</div></div>'; ?>
<div class="row">
	<div class="col-md-12">
		<div class="hpanel hblue">
			<div class="panel-body folder-view">
				<?php
				if(isset($this->categoryRecursiveList) && $this->categoryRecursiveList) {
					echo '<div class="tree">'.$this->categoryRecursiveList.'</div>';
				}
				?>
			</div><!-- /.hpanel-body -->
		</div><!-- /.hpanel -->
	</div>
</div><!-- row -->
