<div class="row">
  <?php
    if(isset($this->message) && $this->message) {
      echo '<div class="col-md-12">'.$this->message.'</div>';
    }

  ?>

  <div class="col-md-12">
      <form role="form" method="post">
        <div class="form-group " >
            <label class="col-sm-3 control-label" >Choose a subdomain name </label>
            <div class="col-sm-9"  >
                <input type="text" class="form-control" name="subdomain_name" id="subdomain_name" placeholder="Sub Domain" value="<?php if(isset($this->frmData['subdomain_name'])) echo $this->frmData['subdomain_name']; ?>" />
                <p id="subdomain_availability_status_cont" class="_red"><?php if(isset($this->errors['subdomain_name'])) echo $this->errors['subdomain_name'];  ?></p>
            </div>
        </div>

        <div class="form-group " >
            <label class="col-sm-3 control-label" ></label>
            <div class="col-sm-9"  >
                <button type="submit" class="btn btn-success">Next</button>
            </div>
        </div>

      </form>
  </div>
</div><!-- row -->
<?php
$this->addOnJs .= "<script>
$(document).on('keyup','#subdomain_name',function(){
  checkSubdomainAvailability();
});
$(document).on('blur','#subdomain_name',function(){
  checkSubdomainAvailability();
});
function checkSubdomainAvailability() {
  var subDomainName = $('#subdomain_name').val();
  var targetUrl = 'check-subdomain-availability';
  $.post(targetUrl,{subdomain_name:subDomainName},function(response){
    $('#subdomain_availability_status_cont').html(response);
  });
}
</script>";
?>
