<div class="modal fade" id="galleryModal"  role="dialog"  aria-hidden="true">
	<div class="modal-dialog modal-lg" >
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Media Library</h4>
			</div>

			<div class="modal-body" >
				test content
			</div><!-- modal-body -->

			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-sm" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
				<button type="button" class="btn btn-primary btn-sm" id="btn_set_fetured_image" data-dismiss="modal" ><i class="fa fa-check"></i> Select Image</button>
			</div>
		</div>
	</div>
</div>
