<?php if(isset($this->message)) echo '<div class="row"><div class="col-lg-12">'.$this->message.'</div></div>'; ?>
<?php if(isset($this->frmData)) $frmData = $this->frmData; if(isset($this->errors)) $errors = $this->errors; ?>

<?php if(isset($this->media) && $this->media) : ?>
<div class="row">
	<form name="frmNews" method="post" action="" >

	<div class="col-sm-9">
		<div class="box">
			<div class="box-body" >
				<div class="form-group col-sm-12">
					<input type="text" value="<?php echo $this->media['file_name']; ?>" id="file_name" name="file_name" disabled="disabled" class="form-control">
				</div>

				<div class="form-group col-sm-12">
					<img src="<?php echo $this->media['file_url'] ?>" style="max-width:100%" />
				</div>

				<div class="form-group col-sm-12">
					<label class="control-label">Caption</label>
					<textarea type="text" id="caption" name="caption" class="form-control"><?php if(isset($this->frmData['caption'])) echo $this->frmData['caption']; ?></textarea>
				</div>

				<div class="form-group col-sm-12">
					<label class="control-label">Alt Text</label>
					<input type="text" value="<?php if(isset($this->frmData['alt_text'])) echo $this->frmData['alt_text']; ?>" id="alt_text" name="alt_text" class="form-control">
				</div>

				<div class="form-group col-sm-12">
					<label class="control-label">Description</label>
					<textarea type="text" id="description" name="description" class="form-control summernote-min"><?php if(isset($this->frmData['description'])) echo stripslashes($this->frmData['description']); ?></textarea>
				</div>
			</div>
			<div class="panel-footer">
				<button type="submit" class="btn btn-primary">Update Changes</button>
			</div>

		</div><!-- hpanel -->
	</div><!-- col-lg-12 -->

	<div class="col-sm-3">
		<div class="box box-info">
			<div class="box-header">
				<h3 class="box-title">Upload Media</h3>
				<div class="box-tools pull-right">
					<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
			</div><!-- /.box-header -->

			<div class="box-body" style="padding:7px !important;">
				<i class="fa fa-calendar"></i> <b><?php echo date('M d Y \a\t H:i',strtotime($this->media['uploaded_on'])); ?></b>
				<br><br> File Size : <b><?php echo $this->media['file_size']; ?> B </b>
				<br><br> File Type : <b><?php echo $this->media['file_type']; ?></b>
				<br><br> Url : <input type="text" value="<?php echo $this->media['file_url']; ?>"  readonly="readonly" class="form-control">
			</div>

    </div>

	</div><!-- col-sm-3 -->

	</form>
</div> <!-- row -->
<?php endif; ?>

<?php
$this->addOnCss = '<link rel="stylesheet" href="'.$this->baseUrl().'/ui_backoffice/vendor/summernote/dist/summernote.css" />';
$this->addOnCss .= '<link rel="stylesheet" href="'.$this->baseUrl().'/ui_backoffice/vendor/summernote/dist/summernote-bs3.css" />';
$this->addOnJs = '<script src="'.$this->baseUrl().'/ui_backoffice/vendor/summernote/dist/summernote.min.js"></script>';
$this->addOnJs .= "<script>
    $(function () {
        // Initialize summernote plugin
        $('.summernote-min').summernote({
			  height: 100,
			  minHeight: null,
			  maxHeight: null,
			  focus: true,
			  toolbar: [
				['style', ['bold', 'italic', 'underline', 'clear']],
				['fontsize', ['fontsize']],
				['color', ['color']],
				['para', ['ul', 'ol', 'paragraph']],
				['height', ['height']]
			  ]
			});

    });
</script>";

?>
