 <?php
 if(isset($this->userSites) && $this->userSites) {
	 foreach($this->userSites as $userSite) {
		 echo $userSite['subdomain_name'];
		 echo ' | ';
		 echo '<a href="'.$this->baseUrl().'/sites?name='.$userSite['subdomain_name'].'" target="_blank">View Site</a>';
		 echo ' | ';
		 echo '<a href="'.$this->baseUrl().'/user/edit-site?name='.$userSite['subdomain_name'].'" target="_blank">Edit Site</a>';
	 }
 }
 ?>
