<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Konnecty CMS - Dashboard</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/Ionicons/css/ionicons.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jvectormap/jquery-jvectormap.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/dist/css/AdminLTE.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/dist/css/skins/_all-skins.min.css">

	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<style>
		._red {
			color:#ff0000;
		}
	</style>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
	<?php if(isset($this->addOnCss) && $this->addOnCss)  echo $this->addOnCss; ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
	<div class="wrapper">
		<header class="main-header">
			<!-- Logo -->
			 <a href="<?php  echo $this->baseUrl(); ?>/backoffice" class="logo">
				<span class="logo-mini"><b>K</b>C</span>
				<span class="logo-lg"><b>KONNECTY</b>CMS</span>
			 </a> <!-- logo -->

			 <!-- Header Navbar: style can be found in header.less -->
			 <nav class="navbar navbar-static-top">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a><!-- sidebar-toggle -->

				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- User Account: style can be found in dropdown.less -->
						<li class="dropdown user user-menu">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							  <img src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
							  <span class="hidden-xs"><?php echo $this->user['name']; ?></span>
							</a><!-- dropdown-toggle -->

							<ul class="dropdown-menu">
								<li class="user-header">
									<img src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
									<p><?php echo $this->user['name']; ?><small>Admin</small></p>
								</li> <!-- user-header -->

								<!-- Menu Footer-->
								<li class="user-footer">
									<div class="pull-left">
									  <a href="<?php echo $this->baseUrl(); ?>/backoffice/users/changepassword" class="btn btn-default btn-flat">Change password</a>
									</div>
									<div class="pull-right">
									  <a href="<?php echo $this->baseUrl(); ?>/backoffice/auth/logout" class="btn btn-default btn-flat">Sign out</a>
									</div>
								</li> <!-- user-footer -->
							</ul><!-- dropdown-menu -->

						</li><!-- dropdown user user-menu -->
					</ul><!-- nav navbar-nav -->
				</div><!-- navbar-custom-menu -->

			 </nav> <!-- navbar navbar-static-top-->
		</header><!-- main-header -->

		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">
			<section class="sidebar">
				<!-- Sidebar user panel -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					</div><!-- pull-left image -->
					<div class="pull-left info">
						<p><?php echo $this->user['name']; ?></p>
						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div><!-- user-panel -->

				<!-- sidebar menu: : style can be found in sidebar.less -->
				<ul class="sidebar-menu" data-widget="tree">
					<li class="header">MAIN NAVIGATION</li>
					<li class="<?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'dashboard' ) echo 'active'; ?>">
					  <a href="<?php echo $this->baseUrl(); ?>/backoffice">
						<i class="fa fa-dashboard"></i> <span>Dashboard</span>
					  </a>
					</li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'users' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-users"></i> <span>Admin Users</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href="<?php echo $this->baseUrl(); ?>/backoffice/users/adduser"><i class="fa fa-circle-o text-red"></i> Add user</a></li>
	            <li><a href="<?php echo $this->baseUrl(); ?>/backoffice/users"><i class="fa fa-circle-o text-green"></i> User list</a></li>
							<li><a href="<?php echo $this->baseUrl(); ?>/backoffice/users/log"><i class="fa fa-circle-o text-yellow"></i> Activity Log</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'themes' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-television"></i> <span>Themes</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href="<?php echo $this->baseUrl(); ?>/backoffice/themes/categories"><i class="fa fa-circle-o text-red"></i> Theme categories</a></li>
							<li><a href="<?php echo $this->baseUrl(); ?>/backoffice/themes/createcategory"><i class="fa fa-circle-o text-green"></i> Create a theme category</a></li>
							<li><a href="<?php echo $this->baseUrl(); ?>/backoffice/themes/index"><i class="fa fa-circle-o text-aqua"></i> Themes</a></li>
							<li><a href="<?php echo $this->baseUrl(); ?>/backoffice/themes/create"><i class="fa fa-circle-o text-yellow"></i> Upload a theme</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'media' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-image"></i> <span>Media</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href="<?php echo $this->baseUrl(); ?>/backoffice/media"><i class="fa fa-circle-o text-red"></i> Manage Media</a></li>
							<li><a href="<?php echo $this->baseUrl(); ?>/backoffice/media/index?upload=1"><i class="fa fa-circle-o text-green"></i> Add New</a></li>
            </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'clients' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-smile-o"></i> <span>Clients</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
							<li><a href=""><i class="fa fa-circle-o text-red"></i> Register a client</a></li>
	            <li><a href=""><i class="fa fa-circle-o text-orange"></i> All Clients</a></li>
							<li><a href=""><i class="fa fa-circle-o text-yellow"></i> Active Clients</a></li>
	            <li><a href=""><i class="fa fa-circle-o text-tan"></i> Inactive Clients</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'subscriptions' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-credit-card"></i> <span>Subscriptions</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href=""><i class="fa fa-circle-o text-aqua"></i> All Subscriptions</a></li>
							<li><a href=""><i class="fa fa-circle-o text-yellow"></i> Expired Subscriptions</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'payments' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-money"></i> <span>Payments</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href=""><i class="fa fa-circle-o text-red"></i> All Payments</a></li>
							<li><a href=""><i class="fa fa-circle-o text-yellow"></i> Unverified Payments</a></li>
							<li><a href=""><i class="fa fa-circle-o text-green"></i> Pending Payments</a></li>
							<li><a href=""><i class="fa fa-circle-o text-orange"></i> Transactions</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'sites' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-opera"></i> <span>Sites</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href=""><i class="fa fa-circle-o text-aqua"></i> All Sites</a></li>
							<li><a href=""><i class="fa fa-circle-o text-red"></i> Archived sites</a></li>
							<li><a href=""><i class="fa fa-circle-o text-sian"></i> Suspended sites</a></li>
							<li><a href=""><i class="fa fa-circle-o text-black"></i> Sub domain sites</a></li>
							<li><a href=""><i class="fa fa-circle-o text-orange"></i> Own domain sites</a></li>
	          </ul>
	        </li>
					<li class="treeview <?php if(isset($this->activeMenuItem) && $this->activeMenuItem == 'configurations' ) echo 'active'; ?>">
	          <a href="#"><i class="fa fa-gears "></i> <span>Configurations</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>
	          <ul class="treeview-menu">
	            <li><a href="<?php echo $this->baseUrl(); ?>/backoffice/configurations"><i class="fa fa-circle-o text-green"></i> System Configurations</a></li>
	          </ul>
	        </li>
				</ul><!-- sidebar-menu -->

			</section><!-- sidebar -->
		</aside><!-- main-sidebar -->

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<section class="content-header">
			  <h1><?php if(isset($this->pageHeading) && $this->pageHeading) echo $this->pageHeading; else echo 'Dashboard'; ?></h1>
			  <ol class="breadcrumb">
				<li><a href="<?php echo $this->baseUrl(); ?>/backoffice"><i class="fa fa-dashboard"></i> Home</a></li>
				<?php
				if(isset($this->breadcrumbs) && $this->breadcrumbs) {
					foreach($this->breadcrumbs as $breadcrumb) {
						echo '<li>';
							echo '<a href="'.$breadcrumb['link'].'" >';
								echo $breadcrumb['label'];
							echo '</a>';
						echo '</li>';
					}
				}
				?>

			  </ol>
			</section><!-- content-header -->

			<section class="content">
				<?php echo $this->layout()->content; ?>
			</section>

		</div><!-- content-wrapper -->

		<footer class="main-footer">
			<div class="pull-right hidden-xs">
			</div>
			<strong>Copyright &copy; 2018-2020</strong>
		</footer>

	</div> <!-- wrapper -->

	<!-- jQuery 3 -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jquery/dist/jquery.min.js"></script>
	<!-- Bootstrap 3.3.7 -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<!-- FastClick -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/fastclick/lib/fastclick.js"></script>
	<!-- AdminLTE App -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/js/adminlte.min.js"></script>
	<!-- Sparkline -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
	<!-- jvectormap  -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
	<!-- SlimScroll -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
	<!-- ChartJS -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/Chart.js/Chart.js"></script>
	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/js/pages/dashboard2.js"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/dist/js/demo.js"></script>
	<?php if(isset($this->addOnJs) && $this->addOnJs)  echo $this->addOnJs; ?>


</body>
</html>
