<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>CMS</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<?php if(isset($this->addOnCss) && $this->addOnCss)  echo $this->addOnCss; ?>
</head>
<body >
	<?php echo $this->layout()->content; ?>
	<?php if(isset($this->addOnJs) && $this->addOnJs)  echo $this->addOnJs; ?>
</body>
</html>
