<?php
@$pageContent = file_get_contents($this->theme['layout_file']);
if(!$pageContent) exit('Something went wrong while fetching site data. Please try again later.');
// assign addon css and scripts
$addOnCss = '<link rel="stylesheet" href="'.$this->baseUrl().'/themes/'.$this->theme['theme_slug'].'/css/style.css">';
$addOnJs = '';
$pageContent = str_replace('@addOnCss;',$addOnCss,$pageContent);
$pageContent = str_replace('@addOnJs;',$addOnJs,$pageContent);

if(isset($this->contents) && $this->contents) {
	foreach($this->contents as $content ) {
		$pageContent = str_replace($content['component_id'],$content['content'],$pageContent);
	}
}

preg_match_all('/@(.*);/', $pageContent, $notRenderedPlaceHolders);
if (isset($notRenderedPlaceHolders[0]) && $notRenderedPlaceHolders[0]) {
	foreach ($notRenderedPlaceHolders[0] as $placeHolder) {
		$placeHolderContent = '<div style="border:1px solid #ff0000; padding:1px;" >'.$placeHolder.'</div>';
		$pageContent = str_replace($placeHolder,$placeHolderContent,$pageContent);
	}
}

echo $pageContent;
?>
