<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>CMS | Login</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  
  </head>
  <br><br>
  <body class="login-page" >
    <div class="login-box">
      <div class="login-logo">
		<h2 style="color:#900;"> CMS - Konnecty</h2>
			<?php /*?><img src="<?php echo $this->baseUrl(); ?>/images/hub_logo.png" style="height:50px;" /><?php */?>

      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <?php if(isset($this->message) && $this->message) echo $this->message; ?>
        <form method="post">
          <div class="form-group has-feedback">
            <input type="text" class="form-control"  name="username" id="username" value="" placeholder="Email"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input name="password" id="password" type="password" class="form-control" value="" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>



      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.3 -->
    <script src="<?php echo $this->baseUrl(); ?>/ui_backoffice/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo $this->baseUrl(); ?>/ui_backoffice/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="<?php echo $this->baseUrl(); ?>/ui_backoffice/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>
