<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Konnecty CMS - Dashboard</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/Ionicons/css/ionicons.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jvectormap/jquery-jvectormap.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/dist/css/AdminLTE.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/ui_alte/dist/css/skins/_all-skins.min.css">

	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<style>
		._red {
			color:#ff0000;
		}
	</style>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
	<?php if(isset($this->addOnCss) && $this->addOnCss)  echo $this->addOnCss; ?>
</head>
<body >
	<?php echo $this->layout()->content; ?>

	<!-- jQuery 3 -->
	<script src="<?php echo $this->baseUrl(); ?>/ui_alte/bower_components/jquery/dist/jquery.min.js"></script>
	<?php if(isset($this->addOnJs) && $this->addOnJs)  echo $this->addOnJs; ?>
</body>
</html>
