<?php

@$pageContent = file_get_contents($this->theme['layout_file']);
if(!$pageContent) exit('Something went wrong while fetching aite data. Please try again later.');
// assign addon css and scripts
$addOnCss = '<link rel="stylesheet" href="'.$this->baseUrl().'/themes/'.$this->theme['theme_slug'].'/css/style.css">';
$addOnJs = '';
$pageContent = str_replace('@addOnCss;',$addOnCss,$pageContent);
$pageContent = str_replace('@addOnJs;',$addOnJs,$pageContent);

if(isset($this->contents) && $this->contents) {
	foreach($this->contents as $content ) {
		$pageContent = str_replace($content['component_id'].';',$content['content'],$pageContent);
	}
}

// remove all not rendered place holders
preg_match_all('/@(.*);/', $pageContent, $notRenderedPlaceHolders);
if (isset($notRenderedPlaceHolders[0]) && $notRenderedPlaceHolders[0]) {
	foreach ($notRenderedPlaceHolders[0] as $placeHolder) {
		$pageContent = str_replace($placeHolder,'',$pageContent);
	}
}

echo $pageContent;
?>
