<div class="row">

	<?php
	if(isset($this->message) && $this->message) {
		echo '<div class="col-md-12">';
			echo $this->message;
		echo '</div>';
	}
	//if(isset($this->user) && $this->user){

	?>

	<div class="col-md-12">
		 <div class="box box-warning">
			<div class="box-header">
				<h3 class="box-title"></h3>
			</div><!-- /.box-header -->
			<!-- form start -->
			<form role="form" action="" method="post" enctype="multipart/form-data">
				<div class="box-body">

                    <div class="form-group " >
                        <label class="col-sm-3 control-label" style="padding-left:0; padding-right:0;" for="type">Enter New Password * </label>
                        <div class="col-sm-6"  >
                            <input type="password" class="form-control" name="password" id="password" placeholder="New Password" value="<?php if(isset($this->frmData['password'])) echo $this->frmData['password']; ?>" />
                            <?php if(isset($this->errors['password'])){ ?>
                                <label class="col-sm-12 control-label" style="padding-left:0; padding-right:0;" for="inputError"><i class="fa fa-times-circle-o"></i> <?php echo '<span class="text-red">'.$this->errors['password'].'</span>'; ?></label>
                            <?php } ?>
                        </div>
                        <div style="clear: both"></div>
                    </div>
                    <div class="form-group " >
                        <label class="col-sm-3 control-label" style="padding-left:0; padding-right:0;" for="type">Retype New Password *  </label>
                        <div class="col-sm-6"  >
                            <input type="password" class="form-control" name="newpassword" id="newpassword" placeholder="Retype New Password " value="<?php if(isset($this->frmData['newpassword'])) echo $this->frmData['newpassword']; ?>" />
                            <?php if(isset($this->errors['newpassword'])){ ?>
                                <label class="col-sm-12 control-label" style="padding-left:0; padding-right:0;" for="inputError"><i class="fa fa-times-circle-o"></i> <?php echo '<span class="text-red">'.$this->errors['newpassword'].'</span>'; ?></label>
                            <?php } ?>
                        </div>
                        <div style="clear: both"></div>
                    </div>

				</div><!-- /.box-body -->

				<div class="box-footer">
					<button type="submit" class="btn btn-primary">Reset</button>
				</div>

			</form>
		</div><!-- /.box -->
	</div><!-- col-md-12 -->
</div><!-- row -->
<?php /*?><?php } else { ?>
<!-- Main content -->
	<section class="content">

		<div class="error-page">
			<h2 class="headline text-danger"><i class="fa fa-warning text-danger"></i></h2>
			<div class="error-content">
				<h3><i class="fa fa-warning text-yellow"></i> Oops! Something went wrong.</h3>
				<p>Something went wrong while accessing the user details.<br><br>
				<a class="btn btn-success btn-sm" href="<?php echo $this->baseUrl(); ?>/institution/user/allusers">Users List</a>
				</p>
			</div>
		</div><!-- /.error-page -->

	</section><!-- /.content -->

<?php } ?><?php */?>
