<div class="row">
	<?php
	if(isset($message) && $message) {
		echo '<div class="col-md-12">';
			echo $message;
		echo '</div>';
	}
	?>
    
  	 <div class="col-md-12">
    	<div class="box box-warning">
			<div class="box-header">
			</div><!-- /.box-header -->
			<div class="box-body table-responsive">
            <table class="table table-striped table-bordered">
              <thead>             
                  <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Date Created</th>
                      <th>User Type</th>
                      <th>Status</th>
                      <th>Actions</th>
                  </tr>
              </thead>   
              <tbody>
               <?php
                if(isset($this->users) && $this->users) {
                  $statusLabels = array(0=>'Disabled' , 1=>'Active');
                  $statusLabelClass = array(0=>'badge bg-red' , 1=>'badge bg-green');

				  foreach($this->users as $entry) {
					  	if($entry['utype']==1) $role = "Super Admin";
						if($entry['utype']==2) $role = "Admin";
						if($entry['utype']==3) $role = "Normal user";
						if($entry['utype']==4) $role = "Manager";
							

					echo '<tr>';
						echo '<td>'.$entry['name'].'</td>';
						echo '<td class="center">'.$entry['email'].'</td>';
						echo '<td class="center">'.date('d M Y',strtotime($entry['date_joined'])).'</td>';
						echo '<td class="center">'.$role.'</td>';
						
						echo '<td class="center"><span class="'.$statusLabelClass[$entry['status']].'">'.$statusLabels[$entry['status']].'</span></td>';
						echo '<td class="center">
								  <a title="View" class="btn-sm btn-primary" href="'.$this->baseUrl().'/backoffice/users/viewuser?id='.$entry['id_user'].'"  ><i class="fa fa-search"></i></a>
								  <a title="Edit" class="btn-sm btn-warning" href="'.$this->baseUrl().'/backoffice/users/adduser?edit='.$entry['id_user'].'"  ><i class="fa fa-edit"></i></a>
								  <a title="Reset Password" class="btn-sm btn-success" href="'.$this->baseUrl().'/backoffice/users/changepassword?id_user='.$entry['id_user'].'"  ><i class="fa fa-lock"></i></a>
								  <a title="Delete" class="btn-sm btn-danger" href="'.$this->baseUrl().'/backoffice/users/deleteuser?del='.$entry['id_user'].'"  ><i class="fa fa-trash"></i></a>
							  </td>';								  
								 //<a title="Allow Access" class="btn-sm btn-info" href="'.$this->baseUrl().'/configurations/allowaccess?user='.$entry['id_user'].'"  ><i class="fa fa-check-circle"></i></a> 
					echo '</tr>';
				  }
			  }	else {
					echo '<tr>';
						echo '<td class="center">Sorry!! No data found</td>';
						echo '<td class="center"></td>';
						echo '<td class="center"></td>';
						echo '<td class="center"></td>';
						echo '<td class="center"></td>';
						echo '<td class="center"></td>';
					echo '</tr>';
			  }              
             ?>
                
              </tbody>
          </table>
           <br/>
          <?php  if(isset($this->pagination) && $this->pagination) echo $this->pagination;  ?>     
          </div>        
        </div>
    </div><!--/span-->

</div>
<script src="<?php echo $this->baseUrl(); ?>/ui_backoffice/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$( ".datepicker" ).datepicker( {format: "yyyy-mm-dd"} );
	});
</script>
					

