
<!-- Main content -->
			<section class="content">
				<div class="row">
					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="info-box">
							<span class="info-box-icon bg-aqua"><i class="ion ion-ios-people-outline"></i></span>

							<div class="info-box-content">
							  <span class="info-box-text">Total Clients</span>
							  <span class="info-box-number"><?php echo isset($this->totalUsers)?$this->totalUsers:0; ?></span>
							</div>
							<!-- /.info-box-content -->
						</div> <!-- info-box -->
					</div><!-- col-md-3 col-sm-6 col-xs-12 -->

					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="info-box">
							<span class="info-box-icon bg-yellow"><i class="glyphicon glyphicon-th"></i></span>

							<div class="info-box-content">
							  <span class="info-box-text">Total Sites</span>
							  <span class="info-box-number"><?php echo isset($this->totalFiles)?$this->totalFiles:0; ?></span>
							</div>
							<!-- /.info-box-content -->
						</div> <!-- info-box -->
					</div><!-- col-md-3 col-sm-6 col-xs-12 -->

					<!-- fix for small devices only -->
					<div class="clearfix visible-sm-block"></div>

					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="info-box">
							<span class="info-box-icon bg-red"><i class="glyphicon glyphicon-picture"></i></span>

							<div class="info-box-content">
							  <span class="info-box-text">Total Themes</span>
							  <span class="info-box-number"><?php echo isset($this->totalImageFiles)?$this->totalImageFiles:0; ?></span>
							</div>
							<!-- /.info-box-content -->
						</div> <!-- info-box -->
					</div><!-- col-md-3 col-sm-6 col-xs-12 -->

					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="info-box">
							<span class="info-box-icon bg-aqua"><i class="glyphicon glyphicon-file"></i></span>

							<div class="info-box-content">
							  <span class="info-box-text">Total Traffic</span>
							  <span class="info-box-number"><?php echo isset($this->totalPdfFiles)?$this->totalPdfFiles:0; ?></span>
							</div>
							<!-- /.info-box-content -->
						</div> <!-- info-box -->
					</div><!-- col-md-3 col-sm-6 col-xs-12 -->
				</div><!-- row -->
			</section><!-- content -->

			<?php /*
			<section>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="box box-primary">
							<div class="box-header ui-sortable-handle" style="cursor: move;">
								<i class="ion ion-clipboard"></i>
								<h3 class="box-title">Users</h3>
							</div>
							<div class="box-body">
								<ul class="todo-list ui-sortable">
									<li style="" class="">
									  <!-- drag handle -->
										<span class="handle ui-sortable-handle">
											<i class="fa fa-ellipsis-v"></i>
											<i class="fa fa-ellipsis-v"></i>
										</span>

										<!-- todo text -->
										<span class="text">Design a nice theme</span>
										<!-- Emphasis label -->
										<small class="label label-danger"><i class="fa fa-clock-o"></i> 2 mins</small>
										<!-- General tools such as edit or delete-->
										<div class="tools">
											<i class="fa fa-edit"></i>
											<i class="fa fa-trash-o"></i>
										</div>
									</li>
								</ul>
							</div>
						</div><!-- box box-primary -->
					</div>
				</div>
			</section>
			*/ ?>
